site_name: Star Technology Wiki
site_url: https://start-dev-team.github.io/StarT-Wiki/
repo_name: Star Technology
repo_url: https://github.com/StarT-Dev-Team/Star-Technology
use_directory_urls: true
theme:
  name: material
  custom_dir: overrides
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/flavicon.ico
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy 
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch

  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: light blue

    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: amber

markdown_extensions:
  - toc:
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          config:
            theme: 'base'
            flowchart: 
              nodeSpacing: 10
              rankSpacing: 20
              curve: basis
              useMaxWidth: false
            themeVariables:
              primaryColor: '#fff'
              primaryTextColor: '#fff'
              primaryBorderColor: '#7e56c2'
              lineColor: '#F8B195'
              fontSize: '16px'
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - mermaid2
  - panzoom:
      full_screen: true


extra_css:
    - assets/styles/styles.css
    - assets/styles/extra.css

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js


nav:
- Welcome to Star Technology:
  - Home: index.md
  - Meet the Team:
      - Developer Team: 'Meet-the-Team/Developer-Team.md'
      - Credits: 'Meet-the-Team/Credits.md'
  - Patch Notes: Patch-Notes.md
  - Challenges: Challenges.md
  - Contributing to this Wiki: 'Contributing-to-This-Wiki.md'

- Resource Gen:
    - 'Resources/index.md'
    - Resource Production:
        - Hydrogen: 'Resources/Resource-Production/Hydrogen.md'
        - Nitrogen: 'Resources/Resource-Production/Nitrogen.md'
        - Oxygen: 'Resources/Resource-Production/Oxygen.md'
    - Resource Production Lines:
        - Oxygen: 'Resources/Resource-Production/Oxygen.md'
    - Resource Producing Machines:
        - Sieving: Resources/Resource-Production-Machines-Lines/Sieving.md
        - Geode Filtration: Resources/Resource-Production-Machines-Lines/GeodeFiltration.md
        - Void Extraction: Resources/Resource-Production-Machines-Lines/Void-Extraction.md
        - Air Distilation: Resources/Resource-Production-Machines-Lines/Air-Distilation.md
        - Drilling Rigs: 'Resources/Resource-Production-Machines-Lines/Drilling Rigs.md'
        - Wood Distilation: Resources/Resource-Production-Machines-Lines/Wood-Distilation.md
        - Barrel: Resources/Resource-Production-Machines-Lines/Industrial-Barrel.md

- Power Gen:
    - Create Power: 'Energy-Generation/Carbon-Brushes-and-Magnets.md'
    - Dynamos: 'Energy-Generation/Dynamos.md'

- Chemical Lines:
    - Chemical-Lines/index.md

    - Plastics: 
        - Chemical-Lines/Plastics/index.md
        - Polyethylene: Chemical-Lines/Plastics/Polyethylene.md
        - Polyvinyl Chloride: Chemical-Lines/Plastics/Polyvinyl-Chloride.md
        - Polytetrafluoroethylene: Chemical-Lines/Plastics/Polytetrafluoroethylene.md
        - Polycaprolactam: Chemical-Lines/Plastics/Polycaprolactam.md
        - Polyvinyl Acetate: Chemical-Lines/Plastics/Polyvinyl-Acetate.md
        - Polyvinyl Butyral: Chemical-Lines/Plastics/Polyvinyl-Butyral.md
        - Epoxy: Chemical-Lines/Plastics/Epoxy.md
        - Polyphenylene Sulfide: Chemical-Lines/Plastics/Polyphenylene-Sulfide.md
        - Polybenzimidazole: Chemical-Lines/Plastics/Polybenzimidazole.md
        - Polyether Ether Ketone: Chemical-Lines/Plastics/PEEK.md
        - Polyimide: Chemical-Lines/Plastics/Polyimide.md
        - PEDOT:PSS: Chemical-Lines/Plastics/PEDOT-PSS.md
        
    - Rubbers:
        - Latex Rubber: Chemical-Lines/Rubbers/Rubber.md
        - Silicone Rubber: Chemical-Lines/Rubbers/Silicone-Rubber.md
        - Styrene Butadiene: Chemical-Lines/Rubbers/Styrene-Butadiene.md

    - Acids: 
        - Sulfuric Acid: Chemical-Lines/Acids/Sulfuric-Acid.md 
        - Acetic Acid: Chemical-Lines/Acids/Acetic-Acid.md
        - Formic Acid: Chemical-Lines/Acids/Formic-Acid.md
        - Hydrochloric Acid: Chemical-Lines/Acids/Hydrochloric-Acid.md
        - Hydrofluoric Acid: Chemical-Lines/Acids/Hydrofluoric-Acid.md
        - Nitric Acid: Chemical-Lines/Acids/Nitric-Acid.md
        - Phosphoric Acid:  Chemical-Lines/Acids/Phosphoric-Acid.md
        - Hypochlorous Acid: Chemical-Lines/Acids/Hypochlorous-Acid.md
        - Fluoroantimonic Acid: Chemical-Lines/Acids/Fluoroantimonic-Acid.md
        - Phthalic Acid: Chemical-Lines/Acids/Phthalic-Acid.md
        - Perchloric Acid: Chemical-Lines/Acids/Perchloric-Acid.md
        - Carbonic Acid: Chemical-Lines/Acids/Carbonic-Acid.md

- Multiblocks:
    - LV Multiblocks: Guides/GregTech/Multiblocks/LV/LV-Multis.md

- Guides:
    - LaserIO:
        - Guides/LaserIO/index.md
        - Tools: Guides/LaserIO/Tools.md
        - Connectors & Nodes: Guides/LaserIO/Connectors-&-Nodes.md
        - Cards: Guides/LaserIO/Cards.md
        - Filters: Guides/LaserIO/Filters.md

    - AE2: Guides/Applied-Energistics-2/AE2-Introduction.md 

    - Gregtech:
        - Electricity: Guides/GregTech/Energy.md
        - Overclocking: Guides/GregTech/Overclock.md
    
    - Transportation:
        - Energy: Guides/Transportation-Methods/Energy.md
        - Fluids: Guides/Transportation-Methods/Fluids.md
        - Items: Guides/Transportation-Methods/Items.md

- FAQ: FAQ.md
